---

- hosts: all
  become: true
  tasks:

  - name: update repository index & install apache2 and php packages (Ubuntu)
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: update repository index & install apache2 and php packages (Fedora)
    dnf:
      update_cache: yes
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
