---

- hosts: all
  become: true
  tasks:

  - name: update repository index (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php packages (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: update repository index (Fedora)
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install apache2 and php packages (Fedora)
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
