---

- hosts: all
  become: true
  tasks:

  - name: update repository index & install apache and php
    package:
      update_cache: yes
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
