---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php for Ubuntu servers
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php for Fedora servers
    dnf:
      update_cache: yes
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
