---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates for Ubuntu servers
    tags: always
    apt:
      upgrade: full
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install updates for Fedora servers
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php for Fedora servers
    tags: apache,httpd,fedora
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb for Ubuntu servers
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install mariadb for Fedora servers
    tags: db,mariadb,fedora
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"


- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
