- name: Install mariadb for Ubuntu servers
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install mariadb for Fedora servers
  tags: db,mariadb,fedora
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Fedora"
